config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"

  get "/auth/:provider/callback", to: "sessions#omniauth"
  get "/session/demo", to: "sessions#demo"
  resource :session, only: [:new, :destroy]
  resources :profiles, only: [:new, :create, :update, :show]
  namespace :api, defaults: { format: :json } do
    put "/cover_letters/:id/generate_pdf", to: "cover_letters#generate_pdf"
    get "/applications/statistics", to: "applications#statistics"
    resources :profiles, only: [:create, :show, :update, :index, :destroy]
    resources :cover_letters, only: [:create, :udpate, :show, :index, :destroy]
    resources :applications, only: [:create, :show, :update, :index]
    resources :users, only: [:show]
    resources :blurbs, only: [:create, :destroy, :show, :index, :update]
    resources :companies, only: [:create, :update, :show, :index, :destroy]
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  before_save :add_http

  has_many :cover_letters

  validates :cover_letter_template, presence: true;

  LINKS = [
    :github,
    :personal_site,
    :linkedin
  ]

  def self.links
    LINKS
  end


  def add_http
    Profile.links.each do |link|
      unless self.send(link)[0..6] == "http://" || self.send(link)[0..7] == "https://"
        self.send(link.to_s + "=", "http://"+  self.send(link))
      end
    end
  end


end

app/controllers/api/profiles_controller.rb
class Api::ProfilesController < ApplicationController

  def index
    @profiles = current_user.profiles
  end

  def show
    @profile = current_user.profiles.find(params[:id])
  end

  def create
    @profile = current_user.profiles.new(profile_params)
    if @profile.save
      render json: @profile, status: 200
    else
      render json: {errors: @profile.errors.full_messages}, status:422
    end
  end

  def update

    @profile = current_user.profiles.find(params[:id])

    if @profile.update(profile_params)
      render json: @profile, status: 200
    else
      render json: {errors: profile.errors.full_messages }, status:422
    end

  end


  def profile_params
    params.require(:profile).permit(:cover_letter_template, :github,:personal_site, :linkedin, :name)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def new
  end


  def show
    @profile = Profile.find(params[:id])
  end

  def create
    @profile = current_user.profile.new(profile_params)
    @profile.save!
    redirect_to root_url
  end

  def update

  end


  def profile_params
    params.require(:profile).permit(:cover_letter_template)
  end

end

app/views/profiles/new.html.erb
<script type="text/javascript">
    function getContent(){
        // document.getElementById("my-textarea").value = document.getElementById("my-content").innerHTML;
        var html = document.getElementById("my-content").innerHTML
        console.log(html);
        $.ajax({
          url: "<%= profiles_url %>",
          method: "POST",
          data: { profile: {
            cover_letter_template: document.getElementById("my-content").innerHTML
          }}
        })
    }


</script>


<div id="my-content" contenteditable="true" style="height: 800px; width: 800px;"><a href="page.html">Some</a> Text</div>

<form id="form" onsubmit="return getContent()">
    <textarea id="my-textarea" style="display:none" name="profile[cover-letter-template]"></textarea>
    <input type="submit" />
</form>

app/views/profiles/show.html.erb
<div class="">
  <%= raw @profile.cover_letter_template%>
</div>